language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:
 - cd Tweets.Web
 - npm install -g bower
 - bower install
 - dotnet restore --verbosity m
 - dotnet build
 - cd ..
 - cd Tweets.Web.Tests
 - dotnet restore --verbosity m
 - dotnet build
 - dotnet test
